# Generated by Django 3.1.3 on 2021-02-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
